Fix upgrade script

diff --git a/etc/upgrade b/etc/upgrade
--- a/etc/upgrade
+++ b/etc/upgrade
@@ -41,10 +41,14 @@ test ${n} -lt 10 && echo >&2 ''
 engine_running && echo 'ERROR: Engine has not stopped.' && exit 1
 echo 'Engine stopped successfully.'
 
+# Exit on error
+set -e
+
 # Compile new engine
 echo 'Compiling new engine...'
 cd build && cmake .. && make master && cd ..
 
 # Execute new engine
 echo 'Executing new engine...'
-nohup ./build/master >> build/master.out & echo $! > build/master.pid
+nohup ./build/master >> build/master.out 2>&1 &
+echo $! > build/master.pid
